name: relatorio-financeiro
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - openpyxl
  - numpy
  - pytest
  - jupyterlab
  - pip
  - pip:
      - streamlit